#!/usr/bin/env bash
# Persist chosen ENABLE_* / ports for upgrades
# shellcheck disable=SC2154

write_install_conf() {
  local f="${FRESHVPS_ETC}/install.conf"
  umask 077
  cat >"${f}" <<EOF
# Generated by FreshVPS install — used on --upgrade
PUBLIC_IP='${PUBLIC_IP:-}'
SSH_PORT='${SSH_PORT:-22}'
ENABLE_HARDENING='${ENABLE_HARDENING:-1}'
ENABLE_SINGBOX='${ENABLE_SINGBOX:-1}'
ENABLE_BLOCKY='${ENABLE_BLOCKY:-1}'
ENABLE_VPN_USERS='${ENABLE_VPN_USERS:-1}'
ENABLE_VPN_API='${ENABLE_VPN_API:-1}'
ENABLE_OPENSOHO='${ENABLE_OPENSOHO:-1}'
ENABLE_KUMA='${ENABLE_KUMA:-0}'
ENABLE_BESZEL='${ENABLE_BESZEL:-0}'
ENABLE_TELEGRAM='${ENABLE_TELEGRAM:-1}'
ENABLE_BACKUP='${ENABLE_BACKUP:-1}'
ENABLE_METRICS='${ENABLE_METRICS:-1}'
ENABLE_LAMPAC='${ENABLE_LAMPAC:-0}'
SINGBOX_VLESS_PORT='${SINGBOX_VLESS_PORT:-443}'
SINGBOX_HY2_PORT='${SINGBOX_HY2_PORT:-8443}'
SINGBOX_REALITY_SNI='${SINGBOX_REALITY_SNI:-www.cloudflare.com}'
BLOCKY_DNS_PORT='${BLOCKY_DNS_PORT:-53}'
OPENSOHO_HTTP_PORT='${OPENSOHO_HTTP_PORT:-8090}'
KUMA_PORT='${KUMA_PORT:-3001}'
BESZEL_PORT='${BESZEL_PORT:-8091}'
VPN_API_PORT='${VPN_API_PORT:-8787}'
VPN_API_BIND='${VPN_API_BIND:-127.0.0.1}'
EOF
  chmod 600 "${f}"
  info "Wrote ${f}"
}

load_install_conf_if_present() {
  local f="${FRESHVPS_ETC}/install.conf"
  if [[ -f "${f}" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "${f}"
    set +a
    info "Loaded ${f}"
  fi
}
