#!/usr/bin/env bash
# Control-plane helper (macOS/Linux laptop) — does not install VPN locally.
# Usage: bash scripts/plan.sh [TREE_ROOT]
set -euo pipefail

ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OUT="${FRESHVPS_PLAN_OUT:-${HOME}/.freshvps/plan}"
mkdir -p "${OUT}"

# shellcheck source=/dev/null
[[ -f "${ROOT}/lib/tui.sh" ]] && source "${ROOT}/lib/tui.sh"

echo "FreshVPS plan — tree=${ROOT}"
echo "Output directory: ${OUT}"
echo

if declare -F tui_input >/dev/null 2>&1; then
  VPS_HOST="$(tui_input "VPS SSH host (user@host or host)" "${VPS_HOST:-root@}")"
  SITE_NAME="$(tui_input "OpenWrt site name (folder)" "site1")"
  LAN_NET="$(tui_input "LAN network prefix (e.g. 10.9.9)" "10.9.9")"
  WIFI_SSID="$(tui_input "Wi-Fi SSID 2.4" "Site-2G")"
  WIFI_PASS="$(tui_input "Wi-Fi password" "CHANGE_THIS_PASSWORD")"
else
  read -r -p "VPS SSH host: " VPS_HOST
  read -r -p "Site name: " SITE_NAME
  read -r -p "LAN prefix: " LAN_NET
  read -r -p "SSID: " WIFI_SSID
  read -r -p "Wi-Fi password: " WIFI_PASS
fi

SITE_DIR="${OUT}/sites/${SITE_NAME}"
mkdir -p "${SITE_DIR}"

cat >"${SITE_DIR}/site.conf" <<EOF
# Generated by scripts/plan.sh — review before deploy
LAN_NETWORK='${LAN_NET}'
LAN_ROUTER_HOST='1'
LAN_NETMASK='255.255.255.0'
WAN_DEVICE='auto'
WAN_PROTO='dhcp'
DHCP_POOL_START='100'
DHCP_POOL_SIZE='50'
DHCP_LEASETIME='12h'
WIFI_COUNTRY='RU'
WIFI_ENCRYPTION='sae'
WIFI_PASSWORD='${WIFI_PASS}'
WIFI_2G_SSID='${WIFI_SSID}'
WIFI_2G_CHANNEL='auto'
WIFI_2G_HTMODE='HT40'
WIFI_5G_SSID='${WIFI_SSID}_5G'
WIFI_5G_CHANNEL='auto'
WIFI_5G_HTMODE='VHT80'
# ENABLE_VPN=1
# EDGE_UPSTREAM_VLESS='vless://...'
# ENABLE_OPENSOHO=1
# OPENSOHO_URL='http://VPS:8090'
EOF

cat >"${OUT}/deploy-hints.txt" <<EOF
# Deploy hints (SSH keys recommended)

# VPS upgrade / install:
ssh ${VPS_HOST} 'curl -fsSL https://raw.githubusercontent.com/PavelNeyman/FreshVPS/main/bootstrap.sh | sudo bash -s -- --upgrade'

# OpenWrt site ${SITE_NAME}:
# scp -r ${ROOT}/openwrt root@ROUTER:/root/freshvps-openwrt
# scp ${SITE_DIR}/site.conf root@ROUTER:/root/freshvps-openwrt/site.conf
# ssh root@ROUTER 'cd /root/freshvps-openwrt && sh install-openwrt.sh'
EOF

echo
echo "Wrote ${SITE_DIR}/site.conf"
echo "Wrote ${OUT}/deploy-hints.txt"
echo "Review passwords; deploy with SSH keys (docs/BOOTSTRAP.md, docs/UPGRADE.md)."
